### ISSUE TITLE
Last(?) Migration script bug

### ISSUE THREAD

**Issue by clburlison** [versx/Brock-WhMgr#197]
The following was required for v5 to function properly.
```
CREATE TABLE `metadata` (
  `key` varchar(255) NOT NULL,
  `value` longtext DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `metadata` (`key`, `value`) VALUES
('LAST_MODIFIED', '1643133618.555');
```

The metadata table was not being generated. You likely wanted this to be created during the startup however the we're setting the migrations manually with `__EFMigrationsHistory` so likely wouldn't be a bad idea to add this to the .sql script.

**Comment by versx** [comment]
Thanks, should be added to the migration script now.
