### ISSUE TITLE
DMs do not work for spawns that have not been IV scanned

### ISSUE THREAD

**Issue by habalushy** [versx/Brock-WhMgr#198]
If I set DM for all spawns (i.e., ".pokeme axew" or selecting Axew and all areas on the webui), spawn DMs do not work if the spawn has not been IV scanned. I've tested this with several pokemon and confirmed the issue. I'm guessing the bot is setting a 0% IV and level 0 minimum, however, unscanned spawns do not meet this criteria. There should be a way to subscribe to all spawns for a certain pokemon (e.g., unown, axew, etc.), regardless of if it has been IV scanned.

**Comment by versx** [comment]
I'm assuming this is with v4? If so, upgrade to v5.

**Comment by versx** [comment]
Closing, feel free to re-open if you're still experiencing the issue with v5.
