### ISSUE TITLE
[Feature] Setting PVP DMs for the desired "final" Pokemon

### ISSUE THREAD

**Issue by habalushy** [versx/Brock-WhMgr#199]
As it works now, setting PVP DMs notifies for the spawns set and any of its evolutions. This is really frustrating when some of the evolutions are undesirable and only one evolution is preferred. For example, on Shinx community day, no one wants PVP DMs for Luxio, only Luxray. However, setting PVP DMs for Shinx (the spawn) gives notifications for both Luxio and Luxray. This forces the user to set custom DMs for manually-entered Luxray IVs (which is tedious), or have a much larger amount of DMs that distract from gameplay, put additional load on the bot devices, and include numerous unnecessary notifications. So, I'd request being able to specify which pokemon in a given family you want to receive PVP DMs for (e.g., requesting venusaur will notify you of bulbasaur, ivysaur, and venusaur spawns that meet PVP criteria for Venusaur).

**Comment by versx** [comment]
I'm assuming this is with v4? If so, upgrade to v5. v5 supports subscribing to whatever the desired evolution is.

**Comment by versx** [comment]
Closing, feel free to re-open if you're still experiencing the issue with v5.

**Comment by habalushy** [comment]
We finally updated to V5 and this feature still doesn’t work as you described

**Comment by versx** [comment]
Thanks, I'll take another look at it tonight.

**Comment by versx** [comment]
@habalushy Should be fixed in #222
