### ISSUE TITLE
PvP subscriptions only work for selected pokemon, not evolutions or pokemon that don't spawn

### ISSUE THREAD

**Issue by habalushy** [versx/Brock-WhMgr#252]
It seems as though you can only set PvP subscriptions for the pokemon you select. For example, if you select Remoraid you only get PvP DMs for Remoraid spawns and not Octillary spawns. If you set subscriptions for Octillary, you only get DMs for wild Octillary and you don't get any Remoraid spawns. This pretty much breaks PvP DMs since several pokemon you can no longer get DMs for (e.g., Altaria).

**Comment by versx** [comment]
🤔 Weird, last time I tested this it worked but I'll try and take a look at it this weekend. Thanks for letting me know.

**Comment by geekygreek7** [comment]
Curious if this has been fixed yet (not getting any PVP Notifications yet)

**Comment by versx** [comment]
> Curious if this has been fixed yet (not getting any PVP Notifications yet)

This should be working now in the `v5-rewrite_feature_pvp_update` with yesterdays commits. Although it is only compatible with RDM's new PvP structure on their develop branch.

**Comment by geekygreek7** [comment]
In order to get pvp working, will I need to create a new RDM instance on their dev branch (instead of master) and use `v5-rewrite_feature_pvp_update` WhMgr branch?

**Comment by versx** [comment]
> In order to get pvp working, will I need to create a new RDM instance on their dev branch (instead of master) and use `v5-rewrite_feature_pvp_update` WhMgr branch?

For testing I'd recommend it or backup your current database and restore the data to a new database incase you need to revert back. Then just change your database name in your `docker-compose.yml` file to the new one.

Although I'm not really sure your issue with PvP is related, PvP channels and subs are working for me with `v5-rewrite` branch but only subscriptions for the base evo at the moment. I posted in the Discord to send me your PvP filter files and discord configs, I think you might have a typo causing the issue tbh.
